### ISSUE TITLE
`transactionExports is not a constructor` - vite-react project

### ISSUE THREAD

**Issue by asiaziola** [ArweaveTeam/arweave-js#167]
Hey :)
One of the projects using Warp SDK reported a bug in their vite-react project (it appears only on production, dev is ok). 

<img width="621" alt="Screenshot 2022-07-25 at 15 33 35" src="https://user-images.githubusercontent.com/22620416/180791023-6e371b20-b3b6-43a3-99ea-14bbbb7d1d14.png">

Error seems to be thrown by the SDK when creating arweave transaction. This is how we do it:

```
  async tx(id: string): Promise<typeof Transaction> {
    const response = await fetch(`${this.baseUrl}/tx/${id}`)
      .then((res) => {
        return res.ok ? res.json() : Promise.reject(res);
      })
      .catch((error) => {
        if (error.body?.message) {
          this.logger.error(error.body.message);
        }
        throw new Error(`Unable to retrieve tx ${id}. ${error.status}. ${error.body?.message}`);
      });

    return new Transaction({
      ...response
    });
  }
```

Error is thrown in the return part when initializing `Transaction`. This is how it is imported:
```
import Transaction from 'arweave/node/lib/transaction';
```

The error is shown also if I'm trying to create a transaction directly in the project (without intermediation of sdk) - importing exactly like shown above and then `new Transaction(tx)`.
If you need any more info or a sample github repo, I'm happy to deliver :)

**Comment by angrymouse** [comment]
Looks like you import transaction class from arweave/*node* module, while using browser enviroment, consider trying *web* or *common*?

**Comment by rosmcmahon** [comment]
hmm. people should really not be doing this deep linking into arweave-js anyhow. this is not the intended use. things get changed in there all the time.

**Comment by ppedziwiatr** [comment]
@rosmcmahon what do you mean? Our SDK is using arweave-js and so has arweave-js in its package.json dependency...how do you suggest to handle this differently?
I guess that's more of an issue with npm dependency system in general :-)

**Comment by rosmcmahon** [comment]
🤔 i've actually seen this same vite import problem with other older cjs libraries. you can fix it in a horrible way adding 
```js
//@ts-ignore
new Transaction.default(response);
```
it's probably possible to add some plugin/config to `vite.config.ts` also. i've yet to figure that out though after following a few issue resolutions in the vitejs github.

but in this case, instead of the deep importing Transaction, maybe you could try using something like:
```ts
const res = await fetch(`${this.baseUrl}/tx/${id}`)
const raw = await res.json()
return arweave.transactions.fromRaw(raw) 
```
this would make your code more future proof as well in case we change arweave-js "internals".

**Comment by rosmcmahon** [comment]
Oh, I should say, it would be ideal to modernise arweave-js a bit. Drop support for NodeJS 12, and switch over to fetch instead of axios, update/drop webpack, for example. There's some very old code though, and it's become spaghetti. Idk if you guys took a look at adding `undici` in the end, but axios specific code is everywhere and there are some issues/oddities in the error handling.

**Comment by rosmcmahon** [comment]
If you spot any easy PRs to fix arweave-js that could be done also?

**Comment by rosmcmahon** [comment]
@asiaziola @ppedziwiatr did you guys get any further with this?

**Comment by asiaziola** [comment]
@rosmcmahon we are currently fighting with web bundlers just to make them compatible with our package. So its somehow connected with this issue. Right after, we will get back to this one and let you know.

**Comment by rosmcmahon** [comment]
ok, i would also suggest trying `arweave.transactions.fromRaw(raw)` instead of deep importing `Transaction`, but i'm interested to see what you come up with!

**Comment by ppedziwiatr** [comment]
> ok, i would also suggest trying `arweave.transactions.fromRaw(raw)` instead of deep importing `Transaction`, but i'm interested to see what you come up with!

Will do, thanks for the hint!

**Comment by rosmcmahon** [comment]
i must have missed your reply, sorry Piotr. 
if you must define the return manually, i guess you could also define the interface/type in your code beside it?

**Comment by rosmcmahon** [comment]
closing this, IIRC it's a bug in Vite. feel free to reopen
