### ISSUE TITLE
Manifest v3 compatibility

### ISSUE THREAD

**Issue by kjesien** [ArweaveTeam/arweave-js#184]
With the beginning of the next year, 2023, Google will only accept Chrome extensions following the Manifest v3. 
`Arweave-js` is used by most of the browser crypto wallets and I wonder if there are plans to make it somehow compliant with this new policy. 
As far as I know, it should mostly consist of replacing the `axios` HTTP client with some other that uses the native `fetch` mechanism as `XMLHttpRequest` won't be available.

**Comment by martonlederer** [comment]
Yes indeed. The new background worker script no longer supports the webcrypto api. 

This would probably require the arweave-js lib to allow the option of defining a custom crypto driver to use.

**Comment by hlolli** [comment]
@martonlederer is there an MDN article that explains this limitation of workers? https://developer.mozilla.org/en-US/

**Comment by angrymouse** [comment]
> Yes indeed. The new background worker script no longer supports the webcrypto api.
> 
> This would probably require the arweave-js lib to allow the option of defining a custom crypto driver to use.

Can we still use WASM there?

**Comment by hlolli** [comment]
I've used wasm inside workers, but because the security restriction differ a lot from one worker type to another. For example in AudioWorklet worker you don't have many of the text encoding functions and no crypto, in new Worker I felt crypto was always available. But that means yes we'll need to polyfill. I think passing crypto, is possible, but it would be simpler for everyone if we'd just fallback to crypto-browserify or smth if global crypto isn't available. But it would increase the bundle size. Which may or may not be a problem, not sure what the footprint is of crypto-browserify, there are other alternatives available as well.

**Comment by martonlederer** [comment]
Update `crypto-browserify` does not work either. Seems like it uses the package [randombytes](https://www.npmjs.com/package/randombytes), which tries to use `window.crypto`, breaking the service worker.

**Comment by kjesien** [comment]
Hello, any updates on this topic? Will you manage to add compatibility with Manifest V3 before the end of the year?

**Comment by rosmcmahon** [comment]
Update. The actual issue is that arweave-js makes extensive and advanced use of Axios library, which is based on XmlHttpRequest. Manifest V3 only supports the newer Fetch API.

There are a couple of 3rd party Axios adapters that allow you to use Fetch API, however none of these appear to be compatible with arweave-js.

**Comment by martonlederer** [comment]
Exactly. I was thinking about rewriting arweave-js as a whole to use fetch. Wdyt?

**Comment by rosmcmahon** [comment]
That would be ideal, but a lot of work! There is some quirky stuff going on when you get into reading chunks and retrying errors.

Two hack-y ideas might be:

1.  to write some wrapping code around fetch to make it behave like Axios does currently
2. write/update an Axios adapter with all the features we need

**Comment by martonlederer** [comment]
Yeah, I was thinking about doing idea 1, but for the future, there's work being done for a complete fetch-adapter [here](https://github.com/axios/axios/pull/5146).

**Comment by kjesien** [comment]
May I ask about `@arconnect/arweave@1.11.6` which got released with [187](https://github.com/ArweaveTeam/arweave-js/pull/187) - does it provide compatibility with Manifest V3?

**Comment by martonlederer** [comment]
@kjesien Partly. Sadly the fetch-adapter used there does not provide full compatibility with all usecases of arweave-js

**Comment by kjesien** [comment]
@martonlederer Thank you for your answer. Are you planning to address this issue before the end of the year?

**Comment by martonlederer** [comment]
Yes, as it is also required for ArConnect

**Comment by kjesien** [comment]
Hello, the new year is just around the corner - did you manage to make some progress on this issue?

**Comment by martonlederer** [comment]
@kjesien Feel free to check out the pull request mentioned above. Help would be much appreciated
