### ISSUE TITLE
Arweave tries to access wrong URLs (*.localhost)

### ISSUE THREAD

**Issue by vporton** [ArweaveTeam/arweave-js#47]
When I run this code as http://zon.localhost/test.html the browser console shows that Arweave tries to access wrong URLs like:

http://zon.localhost/tx_anchor

```html
<html>
    <head>
        <script src="https://unpkg.com/arweave/bundles/web.bundle.min.js"></script>
        <script>
            const arweave = Arweave.init();

            function test() {
                arweave.wallets.generate().then(async (key) => {
                    let transaction = await arweave.createTransaction({
                        data: "x",
                    }, key);
                    await arweave.transactions.sign(transaction, key);
                    const response = await arweave.transactions.post(transaction);
                });
            }

            window.addEventListener('load', test);
        </script>
    </head>
    <body>
        <p>Test</p>
    </body>
</html>
```

**Comment by arweave-kyle** [comment]
Hey @vporton

The library should try to access the arweave api from the current host, then use arweave.net as a fallback when on localhost. You can also skip logic and simply specify a host manually: https://github.com/ArweaveTeam/arweave-js#initialisation-options

I think the defaults aren't working is simply because you're using `zon.localhost` rather than `localhost`
https://github.com/ArweaveTeam/arweave-js/blob/master/src/web/index.ts#L43, this should probably be a bit more flexible, but for now using localhost or manually specifying the init options should work fine as a quick fix.
