### ISSUE TITLE
Arweave-JS doesn't currently work with Webpack 5 in the browser

### ISSUE THREAD

**Issue by acolytec3** [ArweaveTeam/arweave-js#67]
Currently, importing Arweave-JS in a browser based project that uses Webpack 5 will result in a build-time error of the below sort:
ERROR in ./node_modules/arweave/web/lib/merkle.js 9:15-30
Module not found: Error: Can't resolve 'util' in '/home/jim/development/monkeys1/node_modules/arweave/web/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

This can be worked around at present by adding the below to `webpack.configs.js`:
```
module.exports = {
  ...
  plugins: [
    //Polyfill needed nodejs plugins for Arweave-js
    new webpack.ProvidePlugin({
      process: 'process/browser',
    }), new webpack.ProvidePlugin({
      util: 'util/',
    }),
  ...
}
```

and then `npm i --save-dev util process` to add these two node-js polyfill libraries to a given project.

Ideally, these dependencies would be resolved by browser-compatible imports within `arweave/web//lib/merkle`

**Comment by cedriking** [comment]
Hey @acolytec3 , I got the same problem while trying to use esbuild. I have no idea what I did for it to work though. I just deleted my local repo which had a few changes, and cloned it back, and now works fine. We need browser-compatible imports for these because I'm sure that it will appear again for esbuild. 

Thanks for sharing the workaround for webpack. 👍🏼

**Comment by acolytec3** [comment]
@cedriking I believe `util` and `process` should work though I haven't had time to fork arweave-js locally and test it.  I manually installed those two packages and then you stub them into webpack manually and I guess they provide the browser specific implementations for the specific method calls inside `merkle.ts`.  I guess, anyway, I'm a webpack novice so not 100% sure that's what's happening but I'm guessing the actual fix would go something like that.

**Comment by duncanlettuce** [comment]
bundlers not being able to resolve modules like `util` and `process` is altogether somewhat normal when there are cjs packages in the mix and the bundler is targeting the browser. that's my experience, at least. what's less normal in my experience is a bundler complaining about node-specific modules when trying to bundle a browser-friendly library like `arweave-js`. 

if i had to guess, i'd say this can be traced back to the way `arweave-js` is structured/packaged. because the library targets everything — node/web/bundles — it also needs to target different interfaces — e.g. crypto drivers — and does some (IMO)  ornate things to get there, which you can feel out a bit more by taking a look at the build step. 

the ornateness is obviously justified to an extent, but perhaps there's a more effective way of going about it that will serve to make things less brittle?

**Comment by acolytec3** [comment]
@duncanlettuce, I agree. I think the issue here is specific to webpack5 because it [no longer](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed) automatically polyfills those node-specific packages that were done as a matter of course in previous versions.  There may not be a simple way to solve this one and it's beyond my ability/energy to resolve at this point.  I just want to call it out for awareness because Webpack 5 will become standard at some point and this will become a regular issue if not accounted for here.

**Comment by cedriking** [comment]
Hey guys, I released a new version **1.10.4** which should solve this issue. Please let me know if it works correctly from your side.

**Comment by acolytec3** [comment]
Using arweave-js 1.10.5, I still have to install `util` and `process` from npm for it to work.  I was able to remove the webpack config options I noted above though.

**Comment by cedriking** [comment]
New version released. Added all the missing polyfill instead of using a plugin. Tests are passed correctly. Closing this issue and if anything comes up feel free to let us know. Thanks guys for your help! 👍🏼

**Comment by layinka** [comment]
I just started experiencing this again with arweave-js 1.10.15

**Comment by hzhu** [comment]
This seems to still be an issue on `1.10.18` with a vanilla `create-react-app` on Webpack 5.

**Comment by fewwwww** [comment]
> This seems to still be an issue on `1.10.18` with a vanilla `create-react-app` on Webpack 5.

Hi hzhu, how did you solve it? I just cannot make it working with vanilla cra…..

**Comment by hzhu** [comment]
Hi @fewwwww. Yes it should be working. Here's a demo: https://github.com/hzhu/ar-cra-demo
